package main

import (
	"log"
	"net/http"

	_ "github.com/sosvzla/sosvzla.lat/docs" // This will be generated by swag init
	"github.com/sosvzla/sosvzla.lat/adapters"
	"github.com/sosvzla/sosvzla.lat/app"
	"github.com/sosvzla/sosvzla.lat/internal/config"
	"github.com/sosvzla/sosvzla.lat/internal/database"

	httpSwagger "github.com/swaggo/http-swagger/v2"
)

// @title SOS Venezuela Missing Persons API
// @version 1.0
// @description This is a centralized microservice for tracking missing, found, and hospitalized persons in Venezuela.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url https://github.com/marioagutierrez
// @contact.email marioagutierrez@sosvzla.lat

// @license.name MIT
// @license.url https://opensource.org/licenses/MIT

// @host localhost:8080
// @BasePath /
func main() {
	// Load configuration
	cfg, err := config.Load()
	if err != nil {
		log.Fatalf("could not load configuration: %v", err)
	}

	// Create database connection
	db, err := database.NewConnection(cfg.DBConnectionString)
	if err != nil {
		log.Fatalf("could not connect to database: %v", err)
	}
	defer db.Close()

	// Initialize repositories
	personRepo := adapters.NewPostgresPersonRepository(db)
	reportRepo := adapters.NewPostgresReportRepository(db)
	hospitalRepo := adapters.NewPostgresHospitalRepository(db)

	// Initialize service
	searchService := app.NewSearchService(personRepo, reportRepo, hospitalRepo)

	// Initialize HTTP handler
	httpHandler := adapters.NewHTTPHandler(searchService)

	// Set up router
	mux := http.NewServeMux()

	// Register application routes
	httpHandler.RegisterRoutes(mux)

	// Register Swagger route
	// The Swagger UI will be available at /swagger/index.html
	mux.Handle("GET /swagger/", httpSwagger.Handler(
		httpSwagger.URL("http://localhost:8080/swagger/doc.json"), // The url pointing to API definition
	))

	// Enable CORS
	corsHandler := adapters.EnableCORS(mux)

	log.Println("Starting server on :8080")
	log.Println("Swagger UI is available at http://localhost:8080/swagger/index.html")
	if err := http.ListenAndServe(":8080", corsHandler); err != nil {
		log.Fatalf("could not start server: %v", err)
	}
}
